version: '3.7'

services:
  bffapi:
    build:
      context: ./bffapi
      dockerfile: ./Dockerfile
    container_name: simple-blog-mono-bffapi
    ports:
      - 3000:3000
    volumes:
      - fe_node_modules_volume:/workspaces/fe/node_modules
  fe:
    build:
      context: ./fe
      dockerfile: ./Dockerfile
    container_name: simple-blog-mono-fe
    ports:
      - 8080:3000
    depends_on:
      - bffapi
    environment:
      - BFF_API_BASE_URL=http://bffapi:3000
    volumes:
      - fe_node_modules_volume:/workspaces/fe/node_modules
  mysqldb-local:
    build:
      context: ./docker/mysql
      dockerfile: ./Dockerfile
    container_name: simple-blog-mono-mysql-local
    ports:
      - 13306:3306
    volumes:
      - ./docker/mysql/init.d:/docker-entrypoint-initdb.d
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - ./docker/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devdb
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devdev

volumes:
  fe_node_modules_volume:
  bffapi_node_modules_volume:
